extends: standard
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console: 0
  no-unused-vars: 0
  no-undef: 0
  space-before-function-paren: 0
